// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0QFPE-UOSMh6PeYcBT6VwaeBnQnu78qQ',
    appId: '1:158898840327:web:a091c9dcff1d68b531dba2',
    messagingSenderId: '158898840327',
    projectId: 'todo-app-6a0e7',
    authDomain: 'todo-app-6a0e7.firebaseapp.com',
    storageBucket: 'todo-app-6a0e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbF1QGJ6FmD_P7DOBUYWYU8bn6TN5MQwA',
    appId: '1:158898840327:android:ee20a3cb9164acf331dba2',
    messagingSenderId: '158898840327',
    projectId: 'todo-app-6a0e7',
    storageBucket: 'todo-app-6a0e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2jWDbbJ8t_JW5_u7H_Iklva4BPbH2PA',
    appId: '1:158898840327:ios:2d37971de60953e631dba2',
    messagingSenderId: '158898840327',
    projectId: 'todo-app-6a0e7',
    storageBucket: 'todo-app-6a0e7.firebasestorage.app',
    iosBundleId: 'com.example.advanceTodoAppWithBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj2jWDbbJ8t_JW5_u7H_Iklva4BPbH2PA',
    appId: '1:158898840327:ios:2d37971de60953e631dba2',
    messagingSenderId: '158898840327',
    projectId: 'todo-app-6a0e7',
    storageBucket: 'todo-app-6a0e7.firebasestorage.app',
    iosBundleId: 'com.example.advanceTodoAppWithBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0QFPE-UOSMh6PeYcBT6VwaeBnQnu78qQ',
    appId: '1:158898840327:web:b9b178ba1c658bfa31dba2',
    messagingSenderId: '158898840327',
    projectId: 'todo-app-6a0e7',
    authDomain: 'todo-app-6a0e7.firebaseapp.com',
    storageBucket: 'todo-app-6a0e7.firebasestorage.app',
  );
}