// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dvwbWHihu-x9z05Nj8xgDIi126KmsAg',
    appId: '1:1042805198751:web:e6f10e0b8e0761e55f37aa',
    messagingSenderId: '1042805198751',
    projectId: 'fir-integration-38038',
    authDomain: 'fir-integration-38038.firebaseapp.com',
    storageBucket: 'fir-integration-38038.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhh_5yGNOrsj0qLTf4ZnEP281ldVI29CM',
    appId: '1:1042805198751:android:71ba5cd273b033975f37aa',
    messagingSenderId: '1042805198751',
    projectId: 'fir-integration-38038',
    storageBucket: 'fir-integration-38038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArqLGTEFdKPvSQYruo_RQ6Q_ae8bJL3ik',
    appId: '1:1042805198751:ios:a9d844eecb5585cf5f37aa',
    messagingSenderId: '1042805198751',
    projectId: 'fir-integration-38038',
    storageBucket: 'fir-integration-38038.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntegration',
  );
}
