name: final_todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - asset/images/
  uses-material-design: true
